### ISSUE TITLE
No funcionan los envíos nacionales con SD

### ISSUE THREAD

**Issue by Lolosan** [sergiogmuro/correoargentino-api#1]
Muy buen aporte!

No acepta los códigos que empiezan por SD:
{"rta":"KO","code":0,"data":{"msg":"C\u00f3digo de seguimiento mal ingresado."}}

La app tampoco los tiene activos

**Comment by sergiogmuro** [comment]
Gracias @Lolosan ,
voy a investigar un poco mas y en tal caso hago un update

si tenes algun fix pushalo y armate un PR y lo vamos laburando

Saludos

**Comment by sergiogmuro** [comment]
Un update elimino el SD ya que no es soportado por la app al parecer

**Comment by NOMADE55** [comment]
Me encontré con tu repo y voy a hacer un poco de necromancia un año despues, pero:

Al parecer los SD son internamente los Ecommerce.
Yo tengo un envío Ecommerce y al usar la página de Correo Argentino me dice textualmente
```
Resultados de la consulta para la pieza: SD-XXXXXXXXXX-AR 
```
Probe usando el de Ecommerce (con el hash larguísimo) y no lo encuentra, y sorpresivamente usando SD, dice que está mal formateado el número.

Me ánimo a pensar que si movieron la lógica de los ecommerce a otro endpoint, deben darlo de baja sin chequear que se les envía. Probe jugando con cambiar los parametros que envío y me fije que estaba en Laravel 5, así que es capaz dar con como armaron el Validator del otro lado.

Seguiré probando, y si logró algo clavo PR. Buen laburo el de la repo!

**Comment by sergiogmuro** [comment]
> Me encontré con tu repo y voy a hacer un poco de necromancia un año despues, pero:
> 
> Al parecer los SD son internamente los Ecommerce. Yo tengo un envío Ecommerce y al usar la página de Correo Argentino me dice textualmente
> 
> ```
> Resultados de la consulta para la pieza: SD-XXXXXXXXXX-AR 
> ```
> 
> Probe usando el de Ecommerce (con el hash larguísimo) y no lo encuentra, y sorpresivamente usando SD, dice que está mal formateado el número.
> 
> Me ánimo a pensar que si movieron la lógica de los ecommerce a otro endpoint, deben darlo de baja sin chequear que se les envía. Probe jugando con cambiar los parametros que envío y me fije que estaba en Laravel 5, así que es capaz dar con como armaron el Validator del otro lado.
> 
> Seguiré probando, y si logró algo clavo PR. Buen laburo el de la repo!

Me alegro que les ayude el repo.. 
Buenisima la investigacion que estas haciendo, seria un buen aporte..

 saludos
